sudo: required
services:
  - docker

before_install:
  - docker build -t jonasthiesen/docker-react -f Dockerfile.dev .

script:
  - docker run jonasthiesen/docker-react npm run test-ci

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-222642781256"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KE
  secret_access_key:
    secure: "$AWS_SECRET_KEY"